// WS ENVENTS
export const EVNT_PLAYING = 'PLAYING';
export const EVNT_PAUSING = 'PAUSING';
export const EVNT_UPDATE_HOST = 'UPDATE_HOST';
export const EVNT_NEXT_VIDEO = 'NEXT_VIDEO';
export const EVNT_SEEK = 'SEEK';
export const EVNT_SEEK_TO_USER = 'SEEK_TO_USER';
export const EVNT_UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const EVNT_SEEK_TO_ME = 'SEEK_TO_ME';
export const EVNT_UPDATE_QUEUE = 'UPDATE_QUEUE';
export const ENVT_FINSH = 'HANDLE_FINSH';
export const EVNT_USER_UPDATE = 'USER_UPDATE';
export const EVNT_USER_LEAVE = 'USER_LEAVE';
export const EVT_ROOM_EXIT = 'ROOM_EXIT';
export const EVT_VIDEO_CHANGE = 'CHANGE_VIDEO';
export const EVT__CHANGE = 'CHANGE_VIDEO';
export const EVT_ON_PROGRESS_UPDATE = 'ON_PROGRESS_UPDATE';
export const EVNT_UPDATE_STATE = 'UPDATE_STATE';

export const GET_META_SUCCESSFUL = 'GET_META_SUCCESSFUL';
export const UPDATE_META_SUCCESSFUL = 'UPDATE_META_SUCCESSFUL';
export const REJOIN_SUCCESSFUL = 'REJOIN_SUCCESSFUL';
export const PROGRESS_UPDATE = 'PROGRESS_UPDATE';

export const JOIN_SUCCESSFUL = 'JOIN_SUCCESSFUL';
export const ROOM_ERROR = 'ROOM_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const LEAVE_SUCCESSFUL = 'LEAVE_SUCCESSFUL';

export const AUTH_LOGIN = 'AUTH_LOGIN';
