services:

  watch2gether:
    build:
      context: .
    environment:
      DISCORD_TOKEN: CHANGE_ME
      DISCORD_CLIENT_ID: CHANGE_ME
      DISCORD_CLIENT_SECRET: CHANGE_ME
      SESSION_SECRET: CHANGE_ME
      BASE_URL: https://watch2gether.exceptionerror.io
      DEVELOPMENT: 'true'
      DISCORD_ENABLE_NOTIFICATIONS: 'false'
      LISTEN_PORT: 8080
      LOG_LEVEL: info
      RESET: 'true'
      DATABASE_PATH: "/data"
    volumes:
      - w2g_data:/data
    labels:
      caddy: watch2gether.exceptionerror.io
      caddy.reverse_proxy: "{{upstreams 8080}}"

volumes:
  caddy_data: {}
  w2g_data: {}