version: '3'
services:
  watch2gther:
    image: robrotheram/watch2gether:v0.1.1
    container_name: watch2gether
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - 3000:8080
