package events

const (
	EVENT_PLAYING            = "PLAYING"
	EVENT_PAUSING            = "PAUSING"
	EVENT_UPDATE_HOST        = "UPDATE_HOST"
	EVENT_NEXT_VIDEO         = "NEXT_VIDEO"
	EVENT_SEEK               = "SEEK"
	EVENT_SEEK_TO_USER       = "SEEK_TO_USER"
	EVENT_UPDATE_SETTINGS    = "UPDATE_SETTINGS"
	EVENT_SEEK_TO_ME         = "SEEK_TO_ME"
	EVENT_UPDATE_QUEUE       = "UPDATE_QUEUE"
	EVENT_FINISH             = "HANDLE_FINISH"
	EVENT_USER_UPDATE        = "USER_UPDATE"
	EVENT_USER_LEAVE         = "USER_LEAVE"
	EVENT_ROOM_EXIT          = "ROOM_EXIT"
	EVENT_VIDEO_CHANGE       = "CHANGE_VIDEO"
	EVENT__CHANGE            = "CHANGE_VIDEO"
	EVENT_SHUFFLE_QUEUE      = "SHUFFLE_QUEUE"
	EVENT_ON_PROGRESS_UPDATE = "ON_PROGRESS_UPDATE"
	EVENT_UPDATE_STATE       = "UPDATE_STATE"
	EVENT_ADD_VIDEO          = "ADD_NEW_VIDEO"
	EVENT_BOT_LEAVE          = "BOT_LEAVE"

	ROOM_STATUS_RUNNING      = "Running"
	ROOM_STATUS_STOPPING     = "Stopping"
	ROOM_STATUS_STOPPED      = "Stopped"
	ROOM_STATUS_INITIALIZING = "Initializing"
)
