package room

const (
	EVNT_PLAYING           = "PLAYING"
	EVNT_PAUSING           = "PAUSING"
	EVNT_UPDATE_HOST       = "UPDATE_HOST"
	EVNT_NEXT_VIDEO        = "NEXT_VIDEO"
	EVNT_SEEK              = "SEEK"
	EVNT_SEEK_TO_USER      = "SEEK_TO_USER"
	EVNT_UPDATE_SETTINGS   = "UPDATE_SETTINGS"
	EVNT_SEEK_TO_ME        = "SEEK_TO_ME"
	EVNT_UPDATE_QUEUE      = "UPDATE_QUEUE"
	ENVT_FINSH             = "HANDLE_FINSH"
	EVNT_USER_UPDATE       = "USER_UPDATE"
	EVT_ROOM_EXIT          = "ROOM_EXIT"
	EVT_VIDEO_CHANGE       = "CHANGE_VIDEO"
	EVT_ON_PROGRESS_UPDATE = "ON_PROGRESS_UPDATE"

	ROOM_STATUS_RUNNING      = "Running"
	ROOM_STATUS_STOPPING     = "Stopping"
	ROOM_STATUS_STOPPED      = "Stopped"
	ROOM_STATUS_INITIALISING = "Initialising"
)
