export const JOIN_SUCCESSFUL = 'JOIN_SUCCESSFUL';
export const ROOM_ERROR = 'ROOM_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const LEAVE_SUCCESSFUL = 'LEAVE_SUCCESSFUL';

export const UPDATE_SEEK = 'UPDATE_SEEK';
export const SEEK_TO_HOST = "SEEK_TO_HOST";

export const GET_META_SUCCESSFUL = 'GET_META_SUCCESSFUL';
export const UPDATE_META_SUCCESSFUL = 'UPDATE_META_SUCCESSFUL';
export const REJOIN_SUCCESSFUL = 'REJOIN_SUCCESSFUL';