package media

type MediaType string

const (
	VIDEO_TYPE_YT       = "YOUTUBE"
	VIDEO_TYPE_SC       = "SOUNDCLOUD"
	VIDEO_TYPE_MP4      = "MP4"
	VIDEO_TYPE_MP3      = "MP3"
	VIDEO_TYPE_PODCAST  = "PODCAST"
	VIDEO_TYPE_RG       = "RADIO_GARDEN"
	VIDEO_TYPE_PEERTUBE = "PEERTUBE"
)
